reconstruction:
  parameters:
    voxel_size: 0.05
    icp_registration:
      max_iterations: 50
      relative_rmse: 1e-6
    skip_n: 1
    max_depth: 6.0
    remove_stat_outliers:
      nb_neighbors: 20
      std_ratio: 1.0
  camera_parser:
    name: MushroomCameraParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/transformations.json
  image_parser:
    name: MushroomImageParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/images
  depth_parser:
    name: MushroomDepthParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/depth

output_dir: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/rgbd_recon/
save_reconstruction: true
save_format: bin
visualize: false