reconstruction:
  camera_parser:
    name: MushroomCameraParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/transformations.json
  image_parser:
    name: MushroomImageParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/images
  depth_parser:
    name: MushroomDepthParser
    source_path: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/depth

output_dir: ./data/MuSHRoom/room_datasets/classroom/iphone/short_capture/rgbd_recon/